### ISSUE TITLE
Artifactory build info

### ISSUE THREAD

**Issue by louisthomas** [emerald-squad/artifactory-resource#2]
**Is your feature request related to a problem? Please describe.**
I would like to have the feature build-info to track my artifacts and add custom build environment variables.
https://www.jfrog.com/confluence/display/RTF/Build+Integration

**Describe the solution you'd like**
Use JFrog CLI to upload artifact with build info
https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-BuildIntegration

**Comment by gobeila** [comment]
The pull request have been merged. Thank you @jpmorin.
